-- MySQL Script generated by MySQL Workbench
-- Thu Jun 26 21:17:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reserva_salas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reserva_salas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reserva_salas` DEFAULT CHARACTER SET utf8 ;
USE `reserva_salas` ;

-- -----------------------------------------------------
-- Table `reserva_salas`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserva_salas`.`sala` ;

CREATE TABLE IF NOT EXISTS `reserva_salas`.`sala` (
  `idsala` INT NOT NULL AUTO_INCREMENT,
  `capacidade` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(60) NOT NULL,
  `recursos` VARCHAR(100) NOT NULL,
  `codigo_sala` VARCHAR(20) NOT NULL,
  `localizacao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idsala`),
  UNIQUE INDEX `idsala_UNIQUE` (`idsala` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva_salas`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserva_salas`.`usuario` ;

CREATE TABLE IF NOT EXISTS `reserva_salas`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva_salas`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserva_salas`.`reserva` ;

CREATE TABLE IF NOT EXISTS `reserva_salas`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `sala_reservada` VARCHAR(45) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `sala_idsala` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idreserva`, `sala_idsala`, `usuario_idusuario`),
  UNIQUE INDEX `idreserva_UNIQUE` (`idreserva` ASC) ,
  INDEX `fk_reserva_sala_idx` (`sala_idsala` ASC) ,
  INDEX `fk_reserva_usuario1_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_reserva_sala`
    FOREIGN KEY (`sala_idsala`)
    REFERENCES `reserva_salas`.`sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `reserva_salas`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva_salas`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserva_salas`.`evento` ;

CREATE TABLE IF NOT EXISTS `reserva_salas`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nome_evento` VARCHAR(45) NOT NULL,
  `tipo_evento` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `reserva_idreserva` INT NOT NULL,
  `reserva_sala_idsala` INT NOT NULL,
  `reserva_usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idevento`, `reserva_idreserva`, `reserva_sala_idsala`, `reserva_usuario_idusuario`),
  UNIQUE INDEX `idevento_UNIQUE` (`idevento` ASC) ,
  INDEX `fk_evento_reserva1_idx` (`reserva_idreserva` ASC, `reserva_sala_idsala` ASC, `reserva_usuario_idusuario` ASC) ,
  CONSTRAINT `fk_evento_reserva1`
    FOREIGN KEY (`reserva_idreserva` , `reserva_sala_idsala` , `reserva_usuario_idusuario`)
    REFERENCES `reserva_salas`.`reserva` (`idreserva` , `sala_idsala` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
